### ISSUE TITLE
Sensitive information in binary files

### ISSUE THREAD

**Issue by rfuehrer** [generaliinformatik/massprint#2]
Please check if the included binaries contain sensitive information and if they should be removed. In a first/quick check the document properties are filled (-> *.xlsx) . It is unlikely to contain any information beyond what is already publicly known, but we have special requirements for binary objects.

**Comment by dehesselle** [comment]
Yes, I made sure of that **before** committing the sample documents. They are all new documents, created from scratch and not based on company-provided templates. The only information they contain (File|Properties) is my name and our company's name.

**Comment by rfuehrer** [comment]
I agree with you, the settings are set by default, no matter in which LE you work. So we can understand this setting as official and leave it as it is.
